# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_varphi <- function(s, a) {
    .Call(`_ptf_get_varphi`, s, a)
}

get_varphi_next <- function(snew, decisionparm) {
    .Call(`_ptf_get_varphi_next`, snew, decisionparm)
}

get_delta <- function(varphi, varphi_next, theta0, reward, gamma) {
    .Call(`_ptf_get_delta`, varphi, varphi_next, theta0, reward, gamma)
}

maei_c_cont <- function(s, snew, reward, a, gamma, theta0, stepsize, pow1, pow2, maxit, tol, verbose) {
    .Call(`_ptf_maei_c_cont`, s, snew, reward, a, gamma, theta0, stepsize, pow1, pow2, maxit, tol, verbose)
}

vectorize <- function(mat, axis) {
    .Call(`_ptf_vectorize`, mat, axis)
}

vec2mat <- function(vec, row, col, axis) {
    .Call(`_ptf_vec2mat`, vec, row, col, axis)
}

colsum <- function(matrix) {
    .Call(`_ptf_colsum`, matrix)
}

rowsum <- function(matrix) {
    .Call(`_ptf_rowsum`, matrix)
}

matsum <- function(X) {
    .Call(`_ptf_matsum`, X)
}

Frobenius <- function(X) {
    .Call(`_ptf_Frobenius`, X)
}

subsetmatrix <- function(rawmat, rowindex, colindex) {
    .Call(`_ptf_subsetmatrix`, rawmat, rowindex, colindex)
}

beta_beta_inv <- function(V, d, r) {
    .Call(`_ptf_beta_beta_inv`, V, d, r)
}

Calculate_MA <- function(A, M, index, r, k, transpose) {
    .Call(`_ptf_Calculate_MA`, A, M, index, r, k, transpose)
}

Calculate_BetaM <- function(A, M, index, r, k, MA) {
    .Call(`_ptf_Calculate_BetaM`, A, M, index, r, k, MA)
}

update_W <- function(w, inv, beta_m, k) {
    .Call(`_ptf_update_W`, w, inv, beta_m, k)
}

update_A <- function(A, w, m, index, k, MA, MtA) {
    .Call(`_ptf_update_A`, A, w, m, index, k, MA, MtA)
}

E_step <- function(A, w, K, n, index) {
    .Call(`_ptf_E_step`, A, w, K, n, index)
}

obs_loglik <- function(Phi, index) {
    .Call(`_ptf_obs_loglik`, Phi, index)
}

E_step_proj <- function(A, w, K, n, index) {
    .Call(`_ptf_E_step_proj`, A, w, K, n, index)
}

Sparse_E_step <- function(A, w, K, n, index, miu_sparse) {
    .Call(`_ptf_Sparse_E_step`, A, w, K, n, index, miu_sparse)
}

inv_beta_j <- function(A, inv, miu_sparse) {
    .Call(`_ptf_inv_beta_j`, A, inv, miu_sparse)
}

Sparse_update_W <- function(w, inv, beta_m, k, inv_beta_j) {
    .Call(`_ptf_Sparse_update_W`, w, inv, beta_m, k, inv_beta_j)
}

J_AW <- function(AW, miu_sparse) {
    .Call(`_ptf_J_AW`, AW, miu_sparse)
}

Sparse_update_A <- function(A, w, m, index, k, MA, MtA, miu_sparse) {
    .Call(`_ptf_Sparse_update_A`, A, w, m, index, k, MA, MtA, miu_sparse)
}

Expectation <- function(X, A, w, K) {
    .Call(`_ptf_Expectation`, X, A, w, K)
}

loss <- function(X, w, A, k) {
    .Call(`_ptf_loss`, X, w, A, k)
}

UpdateA <- function(exp, w, A, k) {
    .Call(`_ptf_UpdateA`, exp, w, A, k)
}

UpdateW <- function(exp, w, A, k) {
    .Call(`_ptf_UpdateW`, exp, w, A, k)
}

